### ISSUE TITLE
Page and Media Gallery Context/Formats

### ISSUE THREAD

**Issue by craigwillis85** [sonata-project/sandbox#161]
Hi

I'm not sure if this is a bug or not...

If I create a gallery in the 'news' context and select 'news_abstract' or 'news_wide' upload images and then I add a 'sonata.media.block.gallery' add the gallery and select 'news' and 'news_wide' or 'news_abstract' on the frontend It outputs a slideshow.

Am I setting this up right? Shouldn't I see thumbnails with the descriptions rather than a slideshow?

Has anyone got an example of what it should be?

**Comment by jordisala1991** [comment]
This looks more like a question for StackOverflow, also there is no answer since 2014. Closing.

**Comment by gam6itko** [comment]
You need to add wide format in `sonata_media` configuration
```yaml
### packages/sonata_media.yaml
sonata_media:
    contexts:
        news:
            providers:
                - sonata.media.provider.youtube
                - sonata.media.provider.image

            formats:
                small: { width: 150 , quality: 95}
                big:   { width: 500 , quality: 90}
                wide:  { width: 500 , quality: 90} ##customize this as you want
```
