### ISSUE TITLE
default_contexts for sonata_block

### ISSUE THREAD

**Issue by danvbe** [sonata-project/sandbox#398]
I am just starting my way with Sonata and I had an issue while working with the sandbox.
In `app/config/sonata/sonata_block.yml` there is a line to set the default contexts:

```
sonata_block:
    context_manager: sonata.page.block.context_manager
    default_contexts: [cms]
... ...
```

I wasn't able to work with the blocks in admin side (all block type selectors were empty) until I have changed the `default_contexts` value to `[sonata_page_bundle]`.
